from dataclasses import dataclass
from typing import Protocol

from events.generator import GovernanceEvent


CREATE_ISSUE = "CREATE_ISSUE"
COMMENT_ISSUE = "COMMENT_ISSUE"
CLOSE_ISSUE = "CLOSE_ISSUE"
NO_ACTION = "NO_ACTION"

CONTROL_FAILURE = "control-failure"
EXCEPTION_REVIEW = "exception-review"
INTEGRITY_INCIDENT = "integrity-incident"

EVENT_CATEGORIES = {
    "CONTROL_FAILURE_OPENED": CONTROL_FAILURE,
    "CONTROL_FAILURE_CONTINUES": CONTROL_FAILURE,
    "CONTROL_RECOVERY_RECORDED": CONTROL_FAILURE,
    "EXCEPTION_LAPSE_ESCALATION": CONTROL_FAILURE,
    "EXCEPTION_REVIEW_OPENED": EXCEPTION_REVIEW,
    "INTEGRITY_INCIDENT": INTEGRITY_INCIDENT,
}


@dataclass(frozen=True)
class Issue:
    number: int | None
    title: str
    body: str


@dataclass(frozen=True)
class IssueOperation:
    operation: str
    event_id: str
    correlation_id: str
    workflow_category: str
    issue_number: int | None
    title: str
    body: str
    labels: tuple[str, ...]
    reason: str
    workflow_condition: str | None = None


class IssueGateway(Protocol):
    def find_open_issue(self, marker: str) -> Issue | None: ...

    def ensure_labels(self, labels: tuple[str, ...]) -> None: ...

    def has_event_marker(self, issue: Issue, marker: str) -> bool: ...

    def create_issue(
        self, title: str, body: str, labels: tuple[str, ...]
    ) -> Issue: ...

    def comment_issue(self, issue_number: int, body: str) -> None: ...

    def close_issue(self, issue_number: int) -> None: ...


def correlation_id(control_id: str, subject_id: str, category: str) -> str:
    return f"gac-v1:{category}:{control_id}:{subject_id}"


def correlation_marker(identifier: str) -> str:
    return f"<!-- governance-correlation-id: {identifier} -->"


def event_marker(event_id: str) -> str:
    return f"<!-- governance-event-id: {event_id} -->"


def _title(event: GovernanceEvent, category: str, recovered: bool = False) -> str:
    if category == CONTROL_FAILURE:
        title = (
            f"[Governance] {event.control_id} control failure for "
            f"{event.subject_id}"
        )
        return f"{title} (workflow recovered)" if recovered else title
    if category == EXCEPTION_REVIEW:
        return (
            f"[Governance] {event.control_id} approved exception review for "
            f"{event.subject_id}"
        )
    return (
        f"[Governance] {event.control_id} integrity incident for "
        f"{event.subject_id}"
    )


def _event_context(event: GovernanceEvent, identifier: str) -> str:
    transition = event.transition or "Not available"
    review = str(event.requires_human_review).lower()
    return "\n".join(
        [
            f"- Control ID: `{event.control_id}`",
            f"- Subject ID: `{event.subject_id}`",
            f"- Governance outcome: `{event.governance_outcome}`",
            f"- Integrity status: `{event.integrity_status}`",
            f"- Assurance action: `{event.assurance_action}`",
            f"- Transition: `{transition}`",
            f"- Event type: `{event.event_type}`",
            f"- Severity: `{event.severity}`",
            f"- Evaluation date: `{event.evaluation_date}`",
            f"- Human review required: `{review}`",
            f"- Correlation identifier: `{identifier}`",
            "",
            f"Reason: {event.reason}",
        ]
    )


def _body(
    event: GovernanceEvent,
    identifier: str,
    *,
    recovered_missing_workflow: bool = False,
) -> str:
    lines = [
        "This issue was generated by the synthetic Governance as Code demonstration.",
        "Workflow initiation does not constitute governance approval, risk acceptance, "
        "remediation authorization, policy approval, or control-owner attestation.",
        "",
    ]
    if recovered_missing_workflow:
        lines.extend(
            [
                "## Recovered Missing Workflow",
                "",
                "The current condition is a persistent verified control failure, "
                "but no existing correlated open issue was found. The original "
                "CONTROL_FAILURE_OPENED event was not observed by this integration; "
                "this issue reconstructs the missing workflow without inventing "
                "that history.",
                "",
            ]
        )
    elif event.event_type == "EXCEPTION_LAPSE_ESCALATION":
        lines.extend(
            [
                "The approved exception no longer protects this deviation. This "
                "condition requires human governance attention.",
                "",
            ]
        )
    elif event.event_type == "INTEGRITY_INCIDENT":
        lines.extend(
            [
                "Integrity verification returned `MISMATCH` and the assurance "
                "action is `HALT_TRUST`. The affected assurance result should not "
                "be relied upon until the integrity incident is investigated.",
                "",
            ]
        )
    lines.extend(["## Governance Event", "", _event_context(event, identifier), ""])
    lines.extend([event_marker(event.event_id), correlation_marker(identifier)])
    return "\n".join(lines) + "\n"


def _comment(event: GovernanceEvent, identifier: str, heading: str) -> str:
    return "\n".join(
        [
            f"## {heading}",
            "",
            _event_context(event, identifier),
            "",
            "This update was generated by the synthetic Governance as Code demonstration.",
            event_marker(event.event_id),
        ]
    ) + "\n"


def _operation(
    operation: str,
    event: GovernanceEvent,
    category: str,
    identifier: str,
    *,
    issue_number: int | None = None,
    title: str = "",
    body: str = "",
    reason: str,
    workflow_condition: str | None = None,
) -> IssueOperation:
    return IssueOperation(
        operation=operation,
        event_id=event.event_id,
        correlation_id=identifier,
        workflow_category=category,
        issue_number=issue_number,
        title=title,
        body=body,
        labels=("governance-as-code", category),
        reason=reason,
        workflow_condition=workflow_condition,
    )


def plan_event_operations(
    event: GovernanceEvent, gateway: IssueGateway
) -> list[IssueOperation]:
    category = EVENT_CATEGORIES.get(event.event_type)
    if category is None:
        return []
    identifier = correlation_id(event.control_id, event.subject_id, category)
    existing = gateway.find_open_issue(correlation_marker(identifier))

    if event.event_type == "CONTROL_FAILURE_OPENED":
        if existing:
            return [
                _operation(
                    NO_ACTION,
                    event,
                    category,
                    identifier,
                    issue_number=existing.number,
                    reason="A correlated open control-failure issue already exists.",
                )
            ]
        return [
            _operation(
                CREATE_ISSUE,
                event,
                category,
                identifier,
                title=_title(event, category),
                body=_body(event, identifier),
                reason="Create a workflow for the newly opened control failure.",
            )
        ]

    if event.event_type == "CONTROL_FAILURE_CONTINUES":
        if existing:
            if gateway.has_event_marker(existing, event_marker(event.event_id)):
                return [
                    _operation(
                        NO_ACTION,
                        event,
                        category,
                        identifier,
                        issue_number=existing.number,
                        reason="This persistent-failure event is already recorded on the correlated issue.",
                    )
                ]
            return [
                _operation(
                    COMMENT_ISSUE,
                    event,
                    category,
                    identifier,
                    issue_number=existing.number,
                    body=_comment(event, identifier, "Persistent Control Failure Update"),
                    reason="Update the correlated issue with the latest persistent failure.",
                )
            ]
        return [
            _operation(
                CREATE_ISSUE,
                event,
                category,
                identifier,
                title=_title(event, category, recovered=True),
                body=_body(event, identifier, recovered_missing_workflow=True),
                reason=(
                    "Recover a missing workflow for a persistent verified control "
                    "failure; no correlated open issue was found."
                ),
                workflow_condition="RECOVERED_MISSING_OPEN_ISSUE",
            )
        ]

    if event.event_type == "CONTROL_RECOVERY_RECORDED":
        if not existing:
            return [
                _operation(
                    NO_ACTION,
                    event,
                    category,
                    identifier,
                    reason=(
                        "No correlated open issue exists, so prior workflow history "
                        "was not invented and no issue was closed."
                    ),
                )
            ]
        close = _operation(
            CLOSE_ISSUE,
            event,
            category,
            identifier,
            issue_number=existing.number,
            reason="Close the correlated control-failure issue after verified recovery.",
        )
        if gateway.has_event_marker(existing, event_marker(event.event_id)):
            return [close]
        comment = _operation(
            COMMENT_ISSUE,
            event,
            category,
            identifier,
            issue_number=existing.number,
            body=_comment(event, identifier, "Verified Control Recovery"),
            reason="Document the verified recovery before closing the workflow.",
        )
        return [comment, close]

    if event.event_type == "EXCEPTION_LAPSE_ESCALATION":
        if existing:
            if gateway.has_event_marker(existing, event_marker(event.event_id)):
                return [
                    _operation(
                        NO_ACTION,
                        event,
                        category,
                        identifier,
                        issue_number=existing.number,
                        reason="This exception-lapse event is already recorded on the correlated issue.",
                    )
                ]
            return [
                _operation(
                    COMMENT_ISSUE,
                    event,
                    category,
                    identifier,
                    issue_number=existing.number,
                    body=_comment(event, identifier, "Exception Lapse Escalation"),
                    reason="Escalate the exception lapse on the correlated workflow.",
                )
            ]
        return [
            _operation(
                CREATE_ISSUE,
                event,
                category,
                identifier,
                title=_title(event, category),
                body=_body(event, identifier),
                reason="Create a control-failure workflow for the exception lapse.",
            )
        ]

    if existing:
        return [
            _operation(
                NO_ACTION,
                event,
                category,
                identifier,
                issue_number=existing.number,
                reason=f"A correlated open {category} issue already exists.",
            )
        ]
    return [
        _operation(
            CREATE_ISSUE,
            event,
            category,
            identifier,
            title=_title(event, category),
            body=_body(event, identifier),
            reason=f"Create a new {category} workflow.",
        )
    ]


def _execute(operation: IssueOperation, gateway: IssueGateway) -> None:
    if operation.operation == CREATE_ISSUE:
        gateway.ensure_labels(operation.labels)
        gateway.create_issue(operation.title, operation.body, operation.labels)
    elif operation.operation == COMMENT_ISSUE:
        if operation.issue_number is None:
            raise RuntimeError("Cannot comment without an existing GitHub issue number")
        gateway.comment_issue(operation.issue_number, operation.body)
    elif operation.operation == CLOSE_ISSUE:
        if operation.issue_number is None:
            raise RuntimeError("Cannot close without an existing GitHub issue number")
        gateway.close_issue(operation.issue_number)


class _DryRunPlanningGateway:
    def __init__(self, gateway: IssueGateway):
        self.gateway = gateway
        self.virtual_issues: dict[str, Issue] = {}
        self.planned_event_markers: set[str] = set()
        self.closed_correlations: set[str] = set()

    def find_open_issue(self, marker: str) -> Issue | None:
        if marker in self.closed_correlations:
            return None
        return self.virtual_issues.get(marker) or self.gateway.find_open_issue(marker)

    def has_event_marker(self, issue: Issue, marker: str) -> bool:
        if marker in self.planned_event_markers or marker in issue.body:
            return True
        if issue.number is None:
            return False
        return self.gateway.has_event_marker(issue, marker)

    def record(self, operations: list[IssueOperation]) -> None:
        for operation in operations:
            if operation.operation == CREATE_ISSUE:
                marker = correlation_marker(operation.correlation_id)
                self.closed_correlations.discard(marker)
                self.virtual_issues[marker] = Issue(
                    None, operation.title, operation.body
                )
            if operation.operation == CLOSE_ISSUE:
                marker = correlation_marker(operation.correlation_id)
                self.closed_correlations.add(marker)
                self.virtual_issues.pop(marker, None)
            if operation.operation in {CREATE_ISSUE, COMMENT_ISSUE}:
                self.planned_event_markers.add(event_marker(operation.event_id))


def process_events(
    events: list[GovernanceEvent], gateway: IssueGateway, *, dry_run: bool
) -> list[IssueOperation]:
    operations = []
    planning_gateway = _DryRunPlanningGateway(gateway) if dry_run else gateway
    for event in events:
        event_operations = plan_event_operations(event, planning_gateway)
        operations.extend(event_operations)
        if dry_run:
            planning_gateway.record(event_operations)
        else:
            for operation in event_operations:
                _execute(operation, gateway)
    return operations
